# Compile and install libtacsim.
# Copyright Xiaming Chen <chen@xiaming.me>
import os
import sys
import shutil

libdir = os.path.dirname(os.path.realpath('__file__'))

libname = 'libtacsim'
srcfiles = [os.path.join(libdir, 'libtacsim/tacsim.c')]

Library(libname, srcfiles)
SharedLibrary(libname, srcfiles)

if sys.platform.startswith('linux') or \
    sys.platform.startswith('freebsd'):
    shutil.copy(os.path.join(libdir, 'libtacsim.so'), '/usr/local/lib/')
elif sys.platform.startswith('darwin'):
    shutil.copy(os.path.join(libdir, 'libtacsim.dylib'), '/usr/local/lib/')
else:
    print('Unspported system for now: %s' % sys.platform)
    sys.exit(-1)

shutil.copy(os.path.join(libdir, 'libtacsim.a'), '/usr/local/lib/')
shutil.copy(os.path.join(libdir, 'libtacsim/tacsim.h'), '/usr/local/include/')
